# Phundament 4 - Local Development Stack
# ======================================

# Application services
# --------------------

# container to run one-off commands - a dockerized shell
testcli:
  extends:
    file: core-services.yml
    service: cli
  links:
    - 'testnginx:WEB'
    - 'testdb:DB'
  environment:
    YII_ENV: test

testsrc:
  extends:
    file: core-services.yml
    service: src

# The php-fpm server for interpreting php code
testfpm:
  extends:
    file: core-services.yml
    service: fpm
  links:
    - 'testdb:DB'

# The nginx server for serving static files directly
testnginx:
  extends:
    file: core-services.yml
    service: nginx
  ports:
    - "14080:80"
  links:
    - 'testfpm:PHPFPM'
  environment:
    VIRTUAL_HOST: '~^myapp-test\.dev\..*\.xip\.io'

# Data Services
# -------------
testdb:
  extends:
    file: core-services.yml
    service: mariadb

selenium:
    image: selenium/standalone-firefox
    ports:
        - "14444:4444"